# docker-compose.yml
version: '3.3'

services:
  gxc-user-service:
    depends_on:
      - gxc-user-db
    build: ./user-service
    ports:
      - 9092:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "localhost:3306"
      DB_NAME: "gxc_user"
      DB_USER: "test"
      DB_PASSWORD: "test"

  gxc-user-db:
    image: mysql:5.7
    container_name: gxc-user-db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "gxc_user"
      MYSQL_ROOT_PASSWORD: "root"

volumes:
  db_data: {}